### ISSUE TITLE
Awesome Project. Couldn't find tutorial on your website for contact so I apologize for posting here.

### ISSUE THREAD

**Issue by ryan99alero** [AchimPieters/ESP8266-HomeKit-NeoPixel-Light-Strip-EX#1]
Hello, I've recently started making my own homekit devices.  My first was a locking system for my kid's playhouse i built to go on there sliding glass doors. I'm working on an access entry system with an alarm and PIR sensors.  I saw this one on your youtube and it looks like you're using features I'd like to implement into my own light strip.  Mainly the using color buttons to initiate effects.  This is for home personal use and wasn't sure if you'd share your code or if its licensable?  I'm testing on a 5M 300 LED Strand of RGBW SK6812's right now but have plans for 6000 LED at my wife's Salon. I'm finding not many use the RGBW variants and I may just end up getting some RGB's and a secondary strand of Whites.

I totally understand if you don't want to share also.  I'd even appreciate some pointer or if you used another example to implement this if you'd share that info.  That would even be great.

**Comment by AchimPieters** [comment]
You can do it yourself start here: ESP HomeKit SDK – [Full Installation](https://www.studiopieters.nl/esp-homekit-sdk-full-installation/)  and then work your way up, and you can make everything you desire.

**Comment by ryan99alero** [comment]
Thanks for responding.  Yep I've been working from the original esp-homekit distro for awhile just haven't done much more than switches until this project.  Was just curious how you implemented your's.  I've go some idea's on how to accomplish it.  Going to test tonight with Xcode and device simulator so I can trace everything on what its sending back and forth. As I'm guessing its along the line of when a certain color is requested you just loop in an effect instead.
