### ISSUE TITLE
Sourcecode available?

### ISSUE THREAD

**Issue by gabgabe** [AchimPieters/ESP8266-HomeKit-NeoPixel-Light-Strip-EX#2]
Hello, you did a great job, I love how I can choose the FX using the color picker. It makes so easy to automate in HomeKit app.
I'd love to play with the code, I'd make the strip controllable even via RF and choose my leds number. Could you post it?
Thanks 
KISSS

**Comment by AchimPieters** [comment]
@gabgabe all source code is available here: https://github.com/maximkulkin/esp-homekit-demo
